### ISSUE TITLE
Improvements for the website 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/website#1]
- [x] Projects' thumbnails don't look good. I think they are reshaped to a fixed size 
- [x] Some projects have websites, so it might be a good idea to add a button for that in addition to Code and Paper. 
- [x] "we speak different mother tongues" is not accurate, I think all of us speak Arabic and this is the main purpose. 
- [x] "Talks", "People" at navbar not working. 
- [x] The navbar elements are hidden in mobile view, it is not possible to expand them.

**Comment by Eaalghamdi** [comment]
Comment: I made the thumbnails fixed bc projects descriptions are not equal. 

fixes: 3 and 4 are fixed

**Comment by zaidalyafeai** [comment]
@Eaalghamdi we can add white background padding for logos that don't fit.
